# Generated by Django 5.0.3 on 2024-04-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_views"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="views",
        ),
    ]
