# Generated by Django 5.0.3 on 2024-04-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_post_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="default_user_logged_in.png",
                null=True,
                upload_to="",
            ),
        ),
    ]
