# Generated by Django 5.0.3 on 2024-04-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="picture",
            field=models.ImageField(
                blank=True,
                default="img/photo_posts/post_default_images.jpeg",
                null=True,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="img/users_photos_posts/default_user_logged_in.png",
                null=True,
                upload_to="",
            ),
        ),
    ]
