# Generated by Django 5.0.3 on 2024-04-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_post_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
