# Generated by Django 5.0.3 on 2024-04-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_post_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="picture",
            field=models.ImageField(
                blank=True,
                default="users_photos_posts/default_user_logged-in.png",
                null=True,
                upload_to="users_photos_posts/",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="users_photos/default_user_logged_in.png",
                null=True,
                upload_to="users_photos/",
            ),
        ),
    ]
