# Generated by Django 5.0.3 on 2024-04-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_post_picture_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="picture",
            field=models.ImageField(
                blank=True,
                default="users_photos_posts/post_default_images.jpeg",
                null=True,
                upload_to="users_photos_posts",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "Male"), (2, "Female"), (0, "Genderless")],
                null=True,
            ),
        ),
    ]
